services:
  - type: web
    name: stranger-chat-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne backend.asgi:application -b 0.0.0.0 -p $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
