# Generated by Django 5.2.3 on 2025-08-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_created_at_chatroom_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('movies', 'Movies & TV'), ('books', 'Books & Literature'), ('gaming', 'Gaming'), ('travel', 'Travel'), ('food', 'Food & Cooking'), ('fitness', 'Fitness & Health'), ('art', 'Art & Design'), ('science', 'Science'), ('politics', 'Politics'), ('business', 'Business & Finance'), ('education', 'Education'), ('fashion', 'Fashion & Style'), ('nature', 'Nature & Outdoors'), ('philosophy', 'Philosophy'), ('history', 'History'), ('languages', 'Languages'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(blank=True, help_text='Custom name for the room (admin editable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1_interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests for user1'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests for user2'),
        ),
    ]
