# Generated by Django 5.2.5 on 2025-08-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userinterest_chatroom_room_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user1_interests',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2_interests',
        ),
    ]
