# Generated by Django 5.2.3 on 2025-08-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0004_delete_userinterest_remove_chatroom_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user1_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_as_user1', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_as_user2', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
